name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test the Docker Compose version
      run: docker compose version
    - name: Test the Docker-Compose version
      run: docker-compose version
